version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: docker build -t my-node-app .

      - run:
          name: Run Docker Container
          command: docker run -d -p 3000:3000 --name my-node-container my-node-app

      - run:
          name: Wait for the app to start
          command: sleep 5

      - run:
          name: Test if the app is running
          command: curl --fail http://localhost:3000 || (echo "App did not start correctly" && exit 1)

      - run:
          name: Stop Docker Container
          command: docker stop my-node-container

  deploy:
    docker:
      - image: cimg/node:18.17
    steps:
      - setup_remote_docker

      - run:
          name: Login to DockerHub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Tag and Push Docker Image
          command: |
            docker tag my-node-app $DOCKERHUB_USERNAME/my-node-app:latest
            docker push $DOCKERHUB_USERNAME/my-node-app:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
