version: 2.1

orbs:
  docker: circleci/docker@2.2.0  # Assure-toi de spécifier la bonne version de l'orb Docker

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/publish:
          image: $DOCKERHUB_USERNAME/$DOCKERHUB_REPONAME
          update-description: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
