version: 2.1

orbs:
  docker: circleci/docker@2.2.0  # CircleCI Docker orb pour build et push

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    environment:
      DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME  # Variable d'environnement pour le nom d'utilisateur Docker Hub
      DOCKERHUB_PASSWORD: $DOCKERHUB_PASSWORD  # Variable d'environnement pour le mot de passe Docker Hub
    steps:
      - checkout
      - docker/build:
          image: node-js-server  # Le nom de l'image à construire
          dockerfile: Dockerfile  # Le Dockerfile à utiliser
          path: .  # Le répertoire contenant le Dockerfile
      - run:
          name: Docker login to Docker Hub
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - docker/push:
          image: $DOCKERHUB_USERNAME/node-js-server  # Pousser sur Docker Hub avec ce nom d'image
          tag: latest  # Le tag à utiliser pour cette image

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
