version: 2.1

orbs:
  docker: circleci/docker@2.2.0  # Assure-toi que la version correcte est utilisée

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/build-and-push:
          name: Build and Push Docker Image
          image: $DOCKERHUB_USERNAME/$DOCKERHUB_REPONAME
          tag: latest
          path: .
          dockerfile: Dockerfile
          push: true

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
