version: 2.1

orbs:
  docker: circleci/docker@2.2.0  # CircleCI Docker orb pour build et push

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/build:
          image: node-js-server  # Le nom de l'image à construire
          dockerfile: Dockerfile  # Le Dockerfile à utiliser
          path: .  # Le répertoire contenant le Dockerfile
      - docker/push:
          image: $DOCKERHUB_USERNAME/node-js-server  # Pousser sur Docker Hub avec ce nom d'image
          tag: latest  # Le tag à utiliser pour cette image

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
