version: 2.1

orbs:
  docker: circleci/docker@2.2.0  # CircleCI Docker orb for build and push

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - docker/build:
          name: Build Docker image
          image: node-js-server
          dockerfile: Dockerfile
          path: .
      - docker/push:
          name: Push to Docker Hub
          image: $DOCKERHUB_USERNAME/node-js-server
          tag: latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

